### ISSUE TITLE
Installation fails: 'fs' is not in the npm registry.

### ISSUE THREAD

**Issue by Abdelkrim** [woutervroege/node-vcardparser#1]
Dear Wouter, any clue why vcardparser doesn't want to 

npm --version === 1.3.5
node --version === v0.10.15

Thanks in advance for your help

```

npm install vcardparser
npm http GET https://registry.npmjs.org/vcardparser
npm http 200 https://registry.npmjs.org/vcardparser
npm http GET https://registry.npmjs.org/vcardparser/-/vcardparser-1.0.2.tgz
npm http 200 https://registry.npmjs.org/vcardparser/-/vcardparser-1.0.2.tgz
npm http GET https://registry.npmjs.org/fs
npm http 404 https://registry.npmjs.org/fs
npm ERR! 404 'fs' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install" "vcardparser"
npm ERR! cwd /Users//git//myproject
npm ERR! node -v v0.10.15
npm ERR! npm -v 1.3.5
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users//git//myproject/npm-debug.log
npm ERR! not ok code 0
```

**Comment by woutervroege** [comment]
Hey Abdelkrim
thanks for pointing this out. Putting fs in the list of dependencies made the install process fail using recent versions of Node. I removed it from package.json now since fs comes with the core library of node. Just pushed a new version - you should be able to install now.

**Comment by Abdelkrim** [comment]
Thanks that's indeed what i did after done investigation.

Thanks

woutervroege notifications@github.com wrote:

Hey Abdelkrim
thanks for pointing this out. Putting fs in the list of dependencies made the install process fail using recent versions of Node. Just removed it from package.json since fs comes with the core library of node. Just pushed a new version - you should be able to install now.

---
